server:
  port: 8761

spring:
  application:
    name: service-registry
eureka:
  instance:
    hostname: ${GATEWAY_URL:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}
