# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: orderservice
services:
  mysql:
    extends:
      file: ./mysql.yml
      service: mysql
  redis:
    extends:
      file: ./redis.yml
      service: redis
  jhipster-registry:
    extends:
      file: ./jhipster-registry.yml
      service: jhipster-registry
