server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://3.1.6.201:8761/eureka/

management:
  tracing:
    sampling:
      probability: 0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://3.1.6.201:8088"
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
        - id: orderService
          uri: lb://orderService
          predicates:
            - Path=/api/order-items/**,/api/orders/**,/api/payments/**
        - id: productService
          uri: lb://productService
          predicates:
            - Path=/api/products/**,/api/user-activities/**
        - id: userService
          uri: lb://userService
          predicates:
            - Path=/api/authenticate/**,/api/authorities/**,/api/account/**,/api/register/**,/api/addresses/**,/api/admin/**
