# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: N2UzNjMxNmJkMDg3MjQ5MzhlZmFjMTIwMThjYzUzYjlkODhjMWI3ZGE0ZjJkYzY3NjI5MGJmZjE3NTA1MDcxZjFkZjhmYzUyYTI1MjAwMTNmNWZiZmYzN2ZiNDBkODYzMDE1NWNmZWU4ODQ0Mzg5NzlhM2IzNjExMmY5NTRjMTY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
