name: Build and Deploy React App to EC2

on:
  push:
    branches: [ release ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_KEY }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          cd gateway
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest

      - name: Deploy to EC2 via SSH and Docker
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem
          
          if [ ! -d ~/.ssh ]; then
            mkdir -p ~/.ssh
          fi

          if [ -f ~/.ssh/config ]; then
            rm ~/.ssh/config
          fi

          cat <<EOF > ~/.ssh/config
          Host *
          ServerAliveInterval 60
          ServerAliveCountMax 3
          EOF

          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/react-app:latest

            # Stop and remove old container if it exists
            docker stop react-app || true
            docker rm react-app || true

            # Run the new container
            docker run -d --name react-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/react-app:latest
          EOF